# Generated by Django 5.2.9 on 2026-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='paystackpayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], max_length=3),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3),
        ),
    ]
