# Generated by Django 5.2.9 on 2026-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_freelancer', '0005_remove_payout_fee_amount_payout_applied_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(default='USD', editable=False, max_length=3),
        ),
    ]
